version: '3.1'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: vladislavpavlyuk
      POSTGRES_PASSWORD: 621009
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
