CREATE TABLE notice (
                        serial_id        integer generated by default as identity,
                        message          VARCHAR(255),
                        type             VARCHAR(50),
                        processed       BOOLEAN,
                        primary key (serial_id)
)

