CREATE TABLE notice (
    serial_id    INTEGER GENERATED BY DEFAULT AS IDENTITY,
    message      VARCHAR(255),
    type         VARCHAR(50),
    processed    BOOLEAN,
    PRIMARY KEY (serial_id)
);

